# Generated by Django 3.2.8 on 2021-10-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_beer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='beer_id',
        ),
    ]
