# Generated by Django 3.2.8 on 2021-10-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_remove_beer_beer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='first_brewed',
            field=models.CharField(max_length=20),
        ),
    ]
