# Generated by Django 3.2.8 on 2021-10-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_auto_20211021_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTrivialCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('difficulty', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('correct_answer', models.CharField(max_length=120)),
                ('incorrect_answers_1', models.CharField(max_length=120)),
                ('incorrect_answers_2', models.CharField(default=None, max_length=120)),
                ('incorrect_answers_3', models.CharField(default=None, max_length=120)),
            ],
        ),
    ]
